/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Cache Supabase API calls
registerRoute(
    ({ url }) => url.host.includes('supabase.co'),
    new NetworkFirst({
        cacheName: 'supabase-cache',
    })
);

// ===== Installation : prendre le contrôle immédiatement =====
self.addEventListener('install', () => {
    // Force le nouveau SW à remplacer l'ancien immédiatement
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    // Prendre le contrôle de tous les clients immédiatement
    event.waitUntil(self.clients.claim());
});

// ===== Push Notifications (fonctionne même quand l'app est fermée) =====
self.addEventListener('push', (event) => {
    if (!event.data) return;

    try {
        const data = event.data.json();
        const options: NotificationOptions = {
            body: data.body,
            icon: data.icon || '/icons/icon-192.png',
            badge: data.badge || '/icons/icon-192.png',
            tag: data.tag || 'sav-notification',
            data: data.data, // Contient l'URL de redirection
            vibrate: [200, 100, 200],
            requireInteraction: true, // La notification reste affichée jusqu'au clic
            actions: data.actions || [],
            // Relancer l'app si elle est en arrière-plan
            renotify: !!data.tag, // Alerter même si une notif avec le même tag existe
        };

        event.waitUntil(
            self.registration.showNotification(data.title || 'SAV Bruneau', options)
        );
    } catch (err) {
        // Fallback si le JSON est invalide
        const text = event.data?.text() || 'Nouvelle notification';
        event.waitUntil(
            self.registration.showNotification('SAV Bruneau', {
                body: text,
                icon: '/icons/icon-192.png',
                badge: '/icons/icon-192.png',
                requireInteraction: true,
            })
        );
    }
});

// ===== Clic sur la notification → ouvrir l'app sur le bon SAV =====
self.addEventListener('notificationclick', (event: any) => {
    event.notification.close();
    const url = event.notification.data?.url || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // Si une fenêtre est déjà ouverte, on la focalise et on navigue
            for (const client of clientList) {
                if (client.url.includes(self.location.origin) && 'focus' in client) {
                    client.focus();
                    if ('navigate' in client) {
                        return client.navigate(url);
                    }
                    return;
                }
            }
            // Sinon on ouvre une nouvelle fenêtre
            if (self.clients.openWindow) {
                return self.clients.openWindow(url);
            }
        })
    );
});

// Message pour forcer la mise à jour du SW
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
